-- | Temperament: the quietly radical feature.
--
-- A tuning table is twelve cent-offsets from equal temperament, one per
-- pitch class (smart-constructed — the twelve-ness is enforced, the
-- vector-sized dependency is not worth twelve elements). One table serves
-- two outputs:
--
--   * per-note **pitch bend** in the MIDI artifact — for the hardware,
--     which reads no tuning files. Bend is per *channel*, which is why
--     the emitter gives every monophonic lane its own channel.
--   * a rendered **.scl file** — for Surge, which does microtuning
--     natively and serves as ground truth. Same table, two carriers;
--     the round-trip (table -> .scl -> table) is asserted in tests.
--
-- Werckmeister III ships built in: the well-temperament the corpus was
-- written to demonstrate. Carlos re-recorded for want of this; we get it
-- from a lookup table.
--
-- License: GPL-2.0-or-later.
module OTB.Tuning
  ( TuningTable
  , mkTuningTable
  , offsetFor
  , equalTable
  , werckmeister3
  , bendValue
  , parseScl
  , renderScl
  ) where

import Data.Text (Text)
import Data.Text qualified as T
import Data.Text.Read qualified as TR
import OTB.Units (Cents (..))

-- | Offsets from 12TET per pitch class, C first. Opaque; always length 12.
newtype TuningTable = TuningTable [Cents]
  deriving (Eq, Show)

mkTuningTable :: [Cents] -> Either String TuningTable
mkTuningTable cs
  | length cs == 12 = Right (TuningTable cs)
  | otherwise = Left ("tuning table needs 12 offsets, got " <> show (length cs))

offsetFor :: TuningTable -> Int -> Cents
offsetFor (TuningTable cs) pitch = cs !! (pitch `mod` 12)

equalTable :: TuningTable
equalTable = TuningTable (replicate 12 0)

-- | Werckmeister III, C-based. Scale degrees in cents from C:
-- 0, 90.225, 192.18, 294.135, 390.225, 498.045, 588.27, 696.09, 792.18,
-- 888.27, 996.09, 1092.18 — stored as deviation from equal temperament.
werckmeister3 :: TuningTable
werckmeister3 =
  TuningTable
    (zipWith (\w e -> Cents (w - e)) wIII [0, 100 ..])
  where
    wIII =
      [ 0, 90.225, 192.18, 294.135, 390.225, 498.045
      , 588.27, 696.09, 792.18, 888.27, 996.09, 1092.18
      ]

-- | 14-bit pitch-bend value for a cent offset, given the receiver's bend
-- range in semitones (±). Center 8192; clamped to the legal range.
bendValue :: Double -> Cents -> Int
bendValue rangeSemis (Cents c) =
  max 0 (min 16383 (8192 + round (c / (rangeSemis * 100) * 8192)))

-- | Scala .scl subset: '!' comments, description line, count line, then one
-- interval per line — cents ("90.225") or ratio ("256/243") — for degrees
-- 1..n where the last is the octave. Only 12-tone octave scales are
-- accepted; degree k maps to pitch class k, tonic gets 0.
parseScl :: Text -> Either String TuningTable
parseScl src = do
  let content = filter (not . T.isPrefixOf "!") (map T.strip (T.lines src))
  case content of
    (_desc : countLine : rest) -> do
      n <- case TR.decimal countLine of
        Right (v, _) -> Right (v :: Int)
        Left e -> Left ("bad note count: " <> e)
      if n /= 12
        then Left ("only 12-tone scales supported, got " <> show n)
        else do
          vals <- traverse parseInterval (take 12 (filter (not . T.null) rest))
          case vals of
            degrees | length degrees == 12 ->
              -- degrees are intervals to pitch classes 1..12 (last = octave,
              -- which folds to pitch class 0 and must be ~1200)
              let pcCents = 0 : take 11 degrees
               in mkTuningTable (zipWith (\c e -> Cents (c - e)) pcCents [0, 100 ..])
            _ -> Left "fewer than 12 interval lines"
    _ -> Left "truncated .scl"
  where
    parseInterval t
      | T.any (== '/') t
      , (a, b) <- T.breakOn "/" t
      , Right (num, _) <- TR.decimal a
      , Right (den, _) <- TR.decimal (T.drop 1 b)
      , (den :: Integer) > 0 =
          Right (1200 * logBase 2 (fromIntegral (num :: Integer) / fromIntegral den))
      | otherwise = case TR.double t of
          Right (v, _) -> Right v
          Left e -> Left ("bad interval " <> T.unpack t <> ": " <> e)

-- | Render for Surge (and anything else Scala-literate).
renderScl :: Text -> TuningTable -> Text
renderScl name (TuningTable cs) =
  T.unlines $
    [ "! " <> name <> ".scl"
    , "! generated by otb — offsets are exact table values"
    , name
    , "12"
    , "!"
    ]
      <> [ T.pack (show (fromIntegral e + c))
         | (Cents c, e) <- drop 1 (zip cs [0 :: Int, 100 ..])
         ]
      <> ["1200.0"]
